In [5]:
import pandas as pd
excel_file_path=r"Y:\Documents\UNAD\programación para ciencia de datos\Anexo 1 - Base de Datos EXCEL.xlsx"
sheet_name = "BASE DE DATOS" # Specify the sheet name
skiprows = 3           # Skip the first three rows
usecols = 'A:M'        # Only read columns A to C
header = 0             # Use the first row as column headers

df1 = pd.read_excel(excel_file_path, sheet_name=sheet_name, skiprows=skiprows, usecols=usecols, header=header)
df1

,Servicio,Empresa,Turno,Día de la semana,Experiencia del conductor,Formación del Paramédico,Nivel del Paramédico,Cantidad de atenciones,Distancia recorrida (Km),Velocidad máxima (Km/h),Consumo de combustible (Galones),Tiempo en Movimiento (h),Tiempo motor ON (h)
0,1,TAC,D,5,Principiante,4,I,8,78.4,82,3.1,2.8,3.08
1,2,TAD,N,4,Principiante,3,B,5,46.2,89,1.9,2.1,2.31
2,3,TAB,N,4,Experto,4,B,6,62.4,99,2.5,2.6,4.68
3,4,TAB,D,2,Intermedio,3,B,7,70.2,95,3.0,2.6,3.12
4,5,TAC,N,7,Principiante,2,I,8,75.6,87,2.8,2.8,3.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,2196,TAB,D,3,Experto,3,B,6,58.0,100,1.7,2.9,3.19
2196,2197,TAB,N,6,Intermedio,4,B,7,69.6,92,3.0,2.9,4.64
2197,2198,TAB,D,3,Principiante,2,B,5,50.0,86,2.0,2.5,3.75
2198,2199,TAD,D,7,Intermedio,1,B,6,57.2,94,2.6,2.6,2.86
2199,2200,TAD,D,3,Intermedio,1,I,8,84.1,92,3.6,2.9,4.35

In [ ]:
csv_file_path = r"Y:\Documents\UNAD\programación para ciencia de datos\Anexo 2 - Base de Datos CSV.csv"
df2 = pd.read_csv(csv_file_path)
df2